interfaces:
  puzzle_solver:
    name: 8-Puzzle Solver
    description: Solve 8-puzzle configurations using A* search
  puzzle_cli:
    name: 8-Puzzle CLI
    description: Solve 8-puzzle configurations via command line
    module_path: tiferet.contexts.cli
    class_name: CliContext
    attrs:
      cli_repo:
        module_path: tiferet.proxies.yaml.cli
        class_name: CliYamlProxy
        params:
          cli_config_file: app/configs/cli.yml
      cli_service:
        module_path: tiferet.handlers.cli
        class_name: CliHandler
