interfaces:
  puzzle_solver:
    name: 8-Puzzle Solver
    description: Solve the 8-puzzle using A* search with selectable heuristics
  puzzle_cli:
    name: 8-Puzzle CLI
    description: Solve the 8-puzzle via command-line interface
    module_path: tiferet.contexts.cli
    class_name: CliContext
    attrs:
      cli_repo:
        module_path: tiferet.proxies.yaml.cli
        class_name: CliYamlProxy
        params:
          cli_config_file: app/configs/cli.yml
      cli_service:
        module_path: tiferet.handlers.cli
        class_name: CliHandler
